name: Run test suite

on:
   workflow_call:

jobs:
   setup-env:
      uses: ./.github/workflows/setup-env.yml

   run-tests:
      runs-on: ubuntu-latest
      needs: setup-env
      steps:
         - name: Test (this will run for several minutes)
           run: dotnet Faker.sln test  --configuration Release --no-restore --no-build --verbosity normal
