name: Set up environment

on: 
   workflow_call:

jobs:
   setup-env:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v2
      
         - name: Setup .NET Core
           uses: actions/setup-dotnet@v1
           with:
            dotnet-version: 7.0.401
      
         - name: Restore NuGet packages
           run: dotnet restore
      
         - name: Build
           run: dotnet build --configuration Release --no-restore
